Repository wp-cli/widget-command, pull requests merged in 2019-04, with the labels that each got.

#27 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#29 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:testing

#30 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  phpcs.xml.dist
  src/Sidebar_Command.php
  src/Widget_Command.php
  widget-command.php
Labels: scope:testing

#33 Force installation of correct theme
  features/widget-reset.feature
Labels: command:sidebar, scope:testing
